name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag from GerritCodeReview/plugins_github
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Clone GerritCodeReview/plugins_github @ ${{ inputs.tag }}
        with:
          repository: GerritCodeReview/plugins_github
          ref: ${{ inputs.tag }}
      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "maven"
      - name: Build with Maven
        run: mvn install
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          fail_on_unmatched_files: true
          files: github-plugin/target/github-plugin-3.8.0.jar
          make_latest: true
